server:
  port: 8888

spring:
  cloud:
    consul:
      discovery:
        prefer-ip-address: true
        instance-id: ${spring.application.name}:comma,separated,profiles:${server.port}:${random.value}
      host: registry
      port: 8500
    config:
      server:
        git:
          uri: https://github.com/zhangxd1989/spring-boot-cloud
          search-paths: config-repo
          default-label: consul
  rabbitmq:
    host: rabbitmq

security:
  user:
    name: user
    password: ${CONFIG_SERVER_PASSWORD:password}
